// ..
package com.openbravo.pos.catalog;

import com.openbravo.beans.JFlowPanel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.ActionListener;
import javax.swing.*;

//file format
public class JCatalogTab extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    
    private static final int CATALOG_BUTTON_WITH = 96;
    private static final int CATALOG_BUTTON_HEIGHT = 82;

    private final JFlowPanel flowpanel;

    public JCatalogTab() {
        initComponents();

        flowpanel = new JFlowPanel();
        JScrollPane scroll = new JScrollPane(flowpanel);
        scroll.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scroll.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scroll.getVerticalScrollBar().setPreferredSize(new Dimension(35, 35));

        add(scroll, BorderLayout.CENTER);
    }

    @Override
    public void setEnabled(boolean value) {
        flowpanel.setEnabled(value);
        super.setEnabled(value);
    }

    public void addButton(Icon icon, ActionListener actionListener, String text, String textTip) {
        JButton btn = new JButton();
        if(icon != null){
            btn.setIcon(icon);
        }
        addButton(btn, actionListener, text, textTip);
    }
    
    public void addButton(JButton btn, ActionListener actionListener, String text,  String textTip){
        
        if (textTip != null) {
            btn.setToolTipText(textTip);
        }
        
        if(text != null){
            btn.setText(text);
        }

        btn.setFocusPainted(false);
        btn.setFocusable(false);
        btn.setRequestFocusEnabled(false);
        btn.setHorizontalTextPosition(SwingConstants.CENTER);
        btn.setVerticalTextPosition(SwingConstants.CENTER);
        btn.setFont(new java.awt.Font("Arial Bold", 0, 12));
        btn.setMargin(new Insets(2, 2, 2, 2));
        btn.setMaximumSize(new java.awt.Dimension(CATALOG_BUTTON_WITH, CATALOG_BUTTON_HEIGHT));
        btn.setMinimumSize(new java.awt.Dimension(CATALOG_BUTTON_WITH, CATALOG_BUTTON_HEIGHT));
        btn.setPreferredSize(new java.awt.Dimension(CATALOG_BUTTON_WITH, CATALOG_BUTTON_HEIGHT));
        btn.applyComponentOrientation(getComponentOrientation());
        btn.addActionListener(actionListener);

        flowpanel.add(btn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
